FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
        ca-certificates \
        curl \
        git \
        nodejs \
        nodejs-legacy \
        npm \
        openssl
#    && rm -rf /var/lib/apt/lists/*

ENV USER=root
ENV PATH=/root/.cargo/bin:$PATH
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly \
    && rustup target add x86_64-unknown-linux-musl \
    && npm install -g yarn

COPY ui /ui/

RUN cd /ui \
    && cargo build --target=x86_64-unknown-linux-musl --release
RUN cd ui/frontend \
    && yarn \
    && pwd \
    && NODE_ENV=production yarn run build

# Add Docker client (from https://github.com/docker-library/docker/blob/master/1.13/Dockerfile)
ENV DOCKER_BUCKET get.docker.com
ENV DOCKER_VERSION 1.13.1
ENV DOCKER_SHA256 97892375e756fd29a304bd8cd9ffb256c2e7c8fd759e12a55a6336e15100ad75
RUN set -x \
        && curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
        && echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
        && tar -xzvf docker.tgz \
        && mv docker/* /usr/local/bin/ \
        && rmdir docker \
        && rm docker.tgz \
        && docker -v

# use tini as 'init' for this container (https://github.com/krallin/tini)
ENV TINI_VERSION v0.14.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

ENV PLAYGROUND_UI_ADDRESS=0.0.0.0
ENV PLAYGROUND_UI_PORT=80
ENV PLAYGROUND_UI_ROOT=/ui/frontend/build
ENV PLAYGROUND_LOG_FILE=/ui/access-log.csv
ENV RUST_LOG=info
ENV TMPDIR=/tmp

WORKDIR /ui
CMD /ui/target/x86_64-unknown-linux-musl/release/ui

